[package]
name = "DosCollection"
edition = "2024.beta"
license = "Cascade DOL 1.0"
authors = ["Cascade Foundation (dos@cascade.foundation)"]

[dependencies]
CascadeProtocol = { git = "https://github.com/cascadefoundation/cascade_protocol.git", subdir = "package",  rev = "testnet" }
Walrus = { git = "https://github.com/MystenLabs/walrus.git", subdir = "testnet-contracts/walrus", rev = "main"}

[addresses]
dos_collection = "0x0"
